#define SHADOW_TYPE_NONE 0
//#define SHADOW_TYPE_BASIC 1
#define SHADOW_TYPE_DISTORTED 2
#define SHADOW_TYPE_CASCADED 3

#define SHADOW_COLOR_DISABLED 0
#define SHADOW_COLOR_ENABLED 1
#define SHADOW_COLOR_IGNORED 2

#define HAND_LIGHT_NONE 0
#define HAND_LIGHT_VERTEX 1
#define HAND_LIGHT_PIXEL 2

#define DYN_LIGHT_NONE 0
#define DYN_LIGHT_VERTEX 1
#define DYN_LIGHT_PIXEL 2

#define BLOCKTYPE_EMPTY 0u
#define BLOCKTYPE_SOLID 1u
#define BLOCKTYPE_PATHWAY 2u
#define BLOCKTYPE_SLAB_TOP 3u
#define BLOCKTYPE_SLAB_BOTTOM 4u
#define BLOCKTYPE_STAIRS_BOTTOM_N 5u
#define BLOCKTYPE_STAIRS_BOTTOM_E 6u
#define BLOCKTYPE_STAIRS_BOTTOM_S 7u
#define BLOCKTYPE_STAIRS_BOTTOM_W 8u
#define BLOCKTYPE_STAIRS_BOTTOM_INNER_N_W 9u
#define BLOCKTYPE_STAIRS_BOTTOM_INNER_N_E 10u
#define BLOCKTYPE_STAIRS_BOTTOM_INNER_S_W 11u
#define BLOCKTYPE_STAIRS_BOTTOM_INNER_S_E 12u
#define BLOCKTYPE_STAIRS_BOTTOM_OUTER_N_W 13u
#define BLOCKTYPE_STAIRS_BOTTOM_OUTER_N_E 14u
#define BLOCKTYPE_STAIRS_BOTTOM_OUTER_S_W 15u
#define BLOCKTYPE_STAIRS_BOTTOM_OUTER_S_E 16u
#define BLOCKTYPE_STAIRS_TOP_N 17u
#define BLOCKTYPE_STAIRS_TOP_E 18u
#define BLOCKTYPE_STAIRS_TOP_S 19u
#define BLOCKTYPE_STAIRS_TOP_W 20u
#define BLOCKTYPE_STAIRS_TOP_INNER_N_W 21u
#define BLOCKTYPE_STAIRS_TOP_INNER_N_E 22u
#define BLOCKTYPE_STAIRS_TOP_INNER_S_W 23u
#define BLOCKTYPE_STAIRS_TOP_INNER_S_E 24u
#define BLOCKTYPE_STAIRS_TOP_OUTER_N_W 25u
#define BLOCKTYPE_STAIRS_TOP_OUTER_N_E 26u
#define BLOCKTYPE_STAIRS_TOP_OUTER_S_W 27u
#define BLOCKTYPE_STAIRS_TOP_OUTER_S_E 28u
#define BLOCKTYPE_FENCE_POST 29u
#define BLOCKTYPE_FENCE_N 30u
#define BLOCKTYPE_FENCE_E 31u
#define BLOCKTYPE_FENCE_S 32u
#define BLOCKTYPE_FENCE_W 33u
// TODO: add remaining fence types
#define BLOCKTYPE_PRESSURE_PLATE 40u
#define BLOCKTYPE_WALL_POST 41u
// TODO: add remaining fence types
#define BLOCKTYPE_DOOR_N 50u
#define BLOCKTYPE_DOOR_E 51u
#define BLOCKTYPE_DOOR_S 52u
#define BLOCKTYPE_DOOR_W 53u

#define TEX_LIGHT_NOISE noisetex
