#define ENTITY_PLAYER 0
#define ENTITY_BLAZE 10
#define ENTITY_END_CRYSTAL 11
#define ENTITY_IRON_GOLEM 12
#define ENTITY_LIGHTNING_BOLT 13
#define ENTITY_MAGMA_CUBE 14
#define ENTITY_SLIME 15
#define ENTITY_TNT 16
