#define LIGHT_COLOR_AMETHYST_R 0.0
#define LIGHT_COLOR_AMETHYST_G 0.0
#define LIGHT_COLOR_AMETHYST_B 0.0
#define LIGHT_COLOR_SEA_LANTERN_R 0.0
#define LIGHT_COLOR_SEA_LANTERN_G 0.0
#define LIGHT_COLOR_SEA_LANTERN_B 0.0
