#define LIGHT_COLOR_AMETHYST_R 0.464 // [0.0]
#define LIGHT_COLOR_AMETHYST_G 0.227 // [0.0]
#define LIGHT_COLOR_AMETHYST_B 0.788 // [0.0]
const vec3 lightColor_amethyst = vec3(LIGHT_COLOR_AMETHYST_R, LIGHT_COLOR_AMETHYST_G, LIGHT_COLOR_AMETHYST_B);

#define LIGHT_COLOR_BEACON_R 1.000 // [0.0]
#define LIGHT_COLOR_BEACON_G 1.000 // [0.0]
#define LIGHT_COLOR_BEACON_B 1.000 // [0.0]
const vec3 lightColor_beacon = vec3(LIGHT_COLOR_BEACON_R, LIGHT_COLOR_BEACON_G, LIGHT_COLOR_BEACON_B);

// BLAST_FURNACE

#define LIGHT_COLOR_BREWING_STAND_R 0.636 // [0.0]
#define LIGHT_COLOR_BREWING_STAND_G 0.509 // [0.0]
#define LIGHT_COLOR_BREWING_STAND_B 0.179 // [0.0]
const vec3 lightColor_brewingStand = vec3(LIGHT_COLOR_BREWING_STAND_R, LIGHT_COLOR_BREWING_STAND_G, LIGHT_COLOR_BREWING_STAND_B);

// CANDLES

#define LIGHT_COLOR_CAVEVINE_BERRIES_R 0.717 // [0.0]
#define LIGHT_COLOR_CAVEVINE_BERRIES_G 0.541 // [0.0]
#define LIGHT_COLOR_CAVEVINE_BERRIES_B 0.188 // [0.0]
const vec3 lightColor_caveVineBerries = vec3(LIGHT_COLOR_CAVEVINE_BERRIES_R, LIGHT_COLOR_CAVEVINE_BERRIES_G, LIGHT_COLOR_CAVEVINE_BERRIES_B);

#define LIGHT_COLOR_CRYING_OBSIDIAN_R 0.390 // [0.0]
#define LIGHT_COLOR_CRYING_OBSIDIAN_G 0.065 // [0.0]
#define LIGHT_COLOR_CRYING_OBSIDIAN_B 0.646 // [0.0]
const vec3 lightColor_obsidian = vec3(LIGHT_COLOR_CRYING_OBSIDIAN_R, LIGHT_COLOR_CRYING_OBSIDIAN_G, LIGHT_COLOR_CRYING_OBSIDIAN_B);

#define LIGHT_COLOR_END_ROD_R 0.957 // [0.0]
#define LIGHT_COLOR_END_ROD_G 0.929 // [0.0]
#define LIGHT_COLOR_END_ROD_B 0.875 // [0.0]
const vec3 lightColor_endRod = vec3(LIGHT_COLOR_END_ROD_R, LIGHT_COLOR_END_ROD_G, LIGHT_COLOR_END_ROD_B);

// END_STONE_LAMP

// CAMPFIRE

// FIRE

#define LIGHT_COLOR_FROGLIGHT_OCHRE_R 0.768 // [0.0]
#define LIGHT_COLOR_FROGLIGHT_OCHRE_G 0.648 // [0.0]
#define LIGHT_COLOR_FROGLIGHT_OCHRE_B 0.108 // [0.0]
const vec3 lightColor_froglightOchre = vec3(LIGHT_COLOR_FROGLIGHT_OCHRE_R, LIGHT_COLOR_FROGLIGHT_OCHRE_G, LIGHT_COLOR_FROGLIGHT_OCHRE_B);

#define LIGHT_COLOR_FROGLIGHT_PEARLESCENT_R 0.737 // [0.0]
#define LIGHT_COLOR_FROGLIGHT_PEARLESCENT_G 0.435 // [0.0]
#define LIGHT_COLOR_FROGLIGHT_PEARLESCENT_B 0.658 // [0.0]
const vec3 lightColor_froglightPearlescent = vec3(LIGHT_COLOR_FROGLIGHT_PEARLESCENT_R, LIGHT_COLOR_FROGLIGHT_PEARLESCENT_G, LIGHT_COLOR_FROGLIGHT_PEARLESCENT_B);

#define LIGHT_COLOR_FROGLIGHT_VERDANT_R 0.463 // [0.0]
#define LIGHT_COLOR_FROGLIGHT_VERDANT_G 0.763 // [0.0]
#define LIGHT_COLOR_FROGLIGHT_VERDANT_B 0.409 // [0.0]
const vec3 lightColor_froglightVerdant = vec3(LIGHT_COLOR_FROGLIGHT_VERDANT_R, LIGHT_COLOR_FROGLIGHT_VERDANT_G, LIGHT_COLOR_FROGLIGHT_VERDANT_B);

// FURNACE

#define LIGHT_COLOR_GLOWSTONE_R 0.889 // [0.0]
#define LIGHT_COLOR_GLOWSTONE_G 0.611 // [0.0]
#define LIGHT_COLOR_GLOWSTONE_B 0.334 // [0.0]
const vec3 lightColor_glowstone = vec3(LIGHT_COLOR_GLOWSTONE_R, LIGHT_COLOR_GLOWSTONE_G, LIGHT_COLOR_GLOWSTONE_B);

#define LIGHT_COLOR_GLOW_LICHEN_R 0.092 // [0.0]
#define LIGHT_COLOR_GLOW_LICHEN_G 0.217 // [0.0]
#define LIGHT_COLOR_GLOW_LICHEN_B 0.126 // [0.0]
const vec3 lightColor_glowLichen = vec3(LIGHT_COLOR_GLOW_LICHEN_R, LIGHT_COLOR_GLOW_LICHEN_G, LIGHT_COLOR_GLOW_LICHEN_B);

#define LIGHT_COLOR_JACK_O_LANTERN_R 0.768 // [0.0]
#define LIGHT_COLOR_JACK_O_LANTERN_G 0.701 // [0.0]
#define LIGHT_COLOR_JACK_O_LANTERN_B 0.325 // [0.0]
const vec3 lightColor_JackOLantern = vec3(LIGHT_COLOR_JACK_O_LANTERN_R, LIGHT_COLOR_JACK_O_LANTERN_G, LIGHT_COLOR_JACK_O_LANTERN_B);

// LANTERN

// LIGHTING_ROD

#define LIGHT_COLOR_LAVA_R 0.804 // [0.0]
#define LIGHT_COLOR_LAVA_G 0.424 // [0.0]
#define LIGHT_COLOR_LAVA_B 0.149 // [0.0]
const vec3 lightColor_lava = vec3(LIGHT_COLOR_LAVA_R, LIGHT_COLOR_LAVA_G, LIGHT_COLOR_LAVA_B);

#define LIGHT_COLOR_MAGMA_R 0.747 // [0.0]
#define LIGHT_COLOR_MAGMA_G 0.323 // [0.0]
#define LIGHT_COLOR_MAGMA_B 0.110 // [0.0]
const vec3 lightColor_magma = vec3(LIGHT_COLOR_MAGMA_R, LIGHT_COLOR_MAGMA_G, LIGHT_COLOR_MAGMA_B);

#define LIGHT_COLOR_NETHER_PORTAL_R 0.502 // [0.0]
#define LIGHT_COLOR_NETHER_PORTAL_G 0.165 // [0.0]
#define LIGHT_COLOR_NETHER_PORTAL_B 0.831 // [0.0]
const vec3 lightColor_netherPortal = vec3(LIGHT_COLOR_NETHER_PORTAL_R, LIGHT_COLOR_NETHER_PORTAL_G, LIGHT_COLOR_NETHER_PORTAL_B);

#define LIGHT_COLOR_REDSTONE_LAMP_R 0.953 // [0.0]
#define LIGHT_COLOR_REDSTONE_LAMP_G 0.796 // [0.0]
#define LIGHT_COLOR_REDSTONE_LAMP_B 0.496 // [0.0]
const vec3 lightColor_redstoneLamp = vec3(LIGHT_COLOR_REDSTONE_LAMP_R, LIGHT_COLOR_REDSTONE_LAMP_G, LIGHT_COLOR_REDSTONE_LAMP_B);

#define LIGHT_COLOR_REDSTONE_TORCH_R 0.939 // [0.0]
#define LIGHT_COLOR_REDSTONE_TORCH_G 0.305 // [0.0]
#define LIGHT_COLOR_REDSTONE_TORCH_B 0.164 // [0.0]
const vec3 lightColor_redstoneTorch = vec3(LIGHT_COLOR_REDSTONE_TORCH_R, LIGHT_COLOR_REDSTONE_TORCH_G, LIGHT_COLOR_REDSTONE_TORCH_B);

// RESPAWN_ANCHOR

#define LIGHT_COLOR_SCULK_CATALYST_R 0.181 // [0.0]
#define LIGHT_COLOR_SCULK_CATALYST_G 0.358 // [0.0]
#define LIGHT_COLOR_SCULK_CATALYST_B 0.369 // [0.0]
const vec3 lightColor_sculkCatalyst = vec3(LIGHT_COLOR_SCULK_CATALYST_R, LIGHT_COLOR_SCULK_CATALYST_G, LIGHT_COLOR_SCULK_CATALYST_B);

#define LIGHT_COLOR_SEA_LANTERN_R 0.553 // [0.0]
#define LIGHT_COLOR_SEA_LANTERN_G 0.748 // [0.0]
#define LIGHT_COLOR_SEA_LANTERN_B 0.859 // [0.0]
const vec3 lightColor_seaLantern = vec3(LIGHT_COLOR_SEA_LANTERN_R, LIGHT_COLOR_SEA_LANTERN_G, LIGHT_COLOR_SEA_LANTERN_B);

#define LIGHT_COLOR_SEA_PICKLE_R 0.283 // [0.0]
#define LIGHT_COLOR_SEA_PICKLE_G 0.394 // [0.0]
#define LIGHT_COLOR_SEA_PICKLE_B 0.212 // [0.0]
const vec3 lightColor_seaPickle = vec3(LIGHT_COLOR_SEA_PICKLE_R, LIGHT_COLOR_SEA_PICKLE_G, LIGHT_COLOR_SEA_PICKLE_B);

#define LIGHT_COLOR_SHROOMLIGHT_R 0.848 // [0.0]
#define LIGHT_COLOR_SHROOMLIGHT_G 0.469 // [0.0]
#define LIGHT_COLOR_SHROOMLIGHT_B 0.205 // [0.0]
const vec3 lightColor_shroomlight = vec3(LIGHT_COLOR_SHROOMLIGHT_R, LIGHT_COLOR_SHROOMLIGHT_G, LIGHT_COLOR_SHROOMLIGHT_B);

// SMOKER

// SOUL_TORCH

// TORCH
