entity.1=minecraft:player

entity.2=minecraft:current_player

entity.3=minecraft:entity_shadow

entity.10=minecraft:entity_flame

entity.11=allay

entity.12=blaze

entity.13=boat chest_boat acacia_boat birch_boat cherry_boat dark_oak_boat mangrove_boat jungle_boat oak_boat spruce_boat

entity.14=end_crystal

entity.15=glow_squid

entity.16=iron_golem

entity.17=item_frame

entity.18=lightning_bolt

entity.19=magma_cube

entity.20=slime

entity.21=spectral_arrow

entity.22=tnt firework_rocket

entity.23=bigglobe:torch_arrow
