iris.features.required=COMPUTE_SHADERS CUSTOM_IMAGES
iris.features.optional=SEPARATE_HARDWARE_SAMPLERS REVERSED_CULLING ENTITY_TRANSLUCENT BLOCK_EMISSION_ATTRIBUTE FADE_VARIABLE

photonics.enabled=true

#ifdef PHOTONICS_RESTIR_ENABLED
    photonics.lightingMode=restir
#else
    photonics.lightingMode=basic
#endif

#ifdef PHOTONICS_BLOCK_LIGHT_ENABLED
    photonics.enableBlockLight=true
#else
    photonics.enableBlockLight=false
#endif

#ifdef PHOTONICS_BLOCK_TINT_ENABLED
    photonics.alphaMode=block
#else
    photonics.alphaMode=none
#endif

#ifdef PHOTONICS_GI_ENABLED
    photonics.enableGi=true

    #ifdef PHOTONICS_BLOCK_LIGHT_ENABLED
        photonics.enableLightBinning=true
    #endif
#else
    photonics.enableGi=false
#endif


profile.VANILLA =OVERWORLD_SKY:0 LIGHTING_MODE:0 !LIGHTING_COLORED !LIGHTING_REFLECT_ENABLED !SHADOWS_ENABLED !SHADOW_CLOUDS !BLOOM_ENABLED !TONEMAP_ENABLED
profile.ENHANCED=OVERWORLD_SKY:1 LIGHTING_MODE:1  LIGHTING_COLORED  LIGHTING_REFLECT_ENABLED  SHADOWS_ENABLED  SHADOW_CLOUDS  BLOOM_ENABLED  TONEMAP_ENABLED


screen.columns=2
screen=\
    [DEBUG] <profile> \
    <empty> <empty> \
    [WORLD] [MATERIAL] \
    [LIGHTING] [SHADOWS] \
    [EFFECTS] [POST] \
    [MODS]

screen.DEBUG=\
    DEBUG_VIEW DEBUG_WHITEWORLD

screen.WORLD=\
    [WORLD_OUTLINE] [WORLD_OVERWORLD] \
    WIND_ENABLED [WORLD_NETHER] \
    <empty> [WORLD_END]

screen.WORLD_OUTLINE=\
    BLOCK_OUTLINE_TYPE BLOCK_OUTLINE_COLOR_R \
    BLOCK_OUTLINE_WIDTH BLOCK_OUTLINE_COLOR_G \
    BLOCK_OUTLINE_EMISSION BLOCK_OUTLINE_COLOR_B

screen.WORLD_OVERWORLD=\
    OVERWORLD_SKY OVERWORLD_NIGHT_BRIGHTNESS

screen.WORLD_NETHER=\
    NETHER_BRIGHTNESS

screen.WORLD_END=\
    <empty>

screen.MATERIAL=\
    MATERIAL_FORMAT [MATERIAL_PARALLAX] \
    [MATERIAL_EMISSION]

screen.MATERIAL_PARALLAX=\
    MATERIAL_PARALLAX_ENABLED MATERIAL_PARALLAX_TYPE \
    MATERIAL_PARALLAX_DEPTH MATERIAL_PARALLAX_SAMPLES

screen.MATERIAL_EMISSION=\
    MATERIAL_EMISSION_SCALE MATERIAL_EMISSION_POWER

screen.LIGHTING=\
    LIGHTING_MODE LIGHTING_HAND \
    LIGHTING_COLORED LIGHTING_REFLECT_ENABLED \
    LIGHTING_VOXEL_SIZE LIGHTING_MIN

screen.SHADOWS=\
    SHADOWS_ENABLED SHADOW_CLOUDS \
    SHADOW_RESOLUTION shadowDistance \
    SHADOW_PCF_SAMPLES sunPathRotation \
    SHADOW_AMBIENT

screen.EFFECTS=\
    [EFFECT_BLOOM] [EFFECT_SSAO]

screen.EFFECT_SSAO=\
    SSAO_ENABLED SSAO_SAMPLES

screen.EFFECT_BLOOM=\
    BLOOM_ENABLED BLOOM_STRENGTH \
    <empty> BLOOM_LEVELS

screen.POST=\
    [TAA] TONEMAP_ENABLED

screen.TAA=\
    TAA_ENABLED TAA_SHARPNESS

screen.MODS=\
    [MOD_PHOTONICS]

screen.MOD_PHOTONICS=\
    PHOTONICS_RESTIR_ENABLED PHOTONICS_HAND_LIGHT_ENABLED \
    PHOTONICS_REFLECT_ENABLED PHOTONICS_BLOCK_LIGHT_ENABLED \
    PHOTONICS_BLOCK_TINT_ENABLED PHOTONICS_GI_ENABLED

sliders=\
    DEBUG_VIEW \
    OVERWORLD_NIGHT_BRIGHTNESS NETHER_BRIGHTNESS \
    BLOCK_OUTLINE_WIDTH BLOCK_OUTLINE_EMISSION BLOCK_OUTLINE_COLOR_R BLOCK_OUTLINE_COLOR_G BLOCK_OUTLINE_COLOR_B \
    SHADOW_RESOLUTION SHADOW_PCF_SAMPLES shadowDistance sunPathRotation SHADOW_AMBIENT \
    MATERIAL_PARALLAX_DEPTH MATERIAL_PARALLAX_SAMPLES \
    MATERIAL_EMISSION_SCALE MATERIAL_EMISSION_POWER \
    LIGHTING_MIN \
    BLOOM_STRENGTH BLOOM_LEVELS SSAO_SAMPLES TAA_SHARPNESS


voxelizeLightBlocks=true
oldLighting=false
oldHandLight=false

separateAo=true

#if defined(SHADOWS_ENABLED) || defined(LIGHTING_COLORED)
    shadow.enabled=true

    #ifdef LIGHTING_COLORED
        shadow.culling=reversed

        #ifndef SHADOWS_ENABLED
            shadowEntities=false
            shadowPlayer=false
        #endif
    #else
        shadow.culling=true
    #endif
#else
    shadow.enabled=false
#endif

#ifdef WIND_ENABLED
    image.imgBlockWaving=texBlockWaving RED_INTEGER R8UI UNSIGNED_BYTE false false 256 256
#endif

#if defined(LIGHTING_COLORED) || (defined(PHOTONICS) && defined(PHOTONICS_BLOCK_LIGHT_ENABLED))
    image.imgBlockLight=texBlockLight RGBA RGBA8 UNSIGNED_BYTE false false 256 256
#else
    program.world-1/setup1.enabled=false
    program.world0/setup1.enabled=false
    program.world1/setup1.enabled=false
#endif

#ifdef SHADOW_CLOUDS
    customTexture.texClouds=minecraft:textures/environment/clouds.png
    image.imgCloudShadow=texCloudShadow RED R16F HALF_FLOAT false false 256 256
#else
    program.world0/setup2.enabled=false
#endif

#if LIGHTING_MODE == 1
    image.imgSkyTransmit=texSkyTransmit RGB RGBA16F HALF_FLOAT false false 256 64
    image.imgSkyIrradiance=texSkyIrradiance RGB RGBA16F HALF_FLOAT false false 24 6 2
#else
    program.world0/setup3.enabled=false
    program.world0/setup4.enabled=false
#endif

#ifdef LIGHTING_COLORED
    image.imgBlockMask=texBlockMask RED_INTEGER R16UI UNSIGNED_SHORT false false 256 256

    #if   LIGHTING_VOXEL_SIZE == 256
        image.imgVoxels=texVoxels RED_INTEGER R16UI UNSIGNED_SHORT true false 256 256 256
        image.imgFloodFillA=texFloodFillA RGBA RGBA8 UNSIGNED_BYTE false false 256 256 256
        image.imgFloodFillB=texFloodFillB RGBA RGBA8 UNSIGNED_BYTE false false 256 256 256
    #elif LIGHTING_VOXEL_SIZE == 128
        image.imgVoxels=texVoxels RED_INTEGER R16UI UNSIGNED_SHORT true false 128 128 128
        image.imgFloodFillA=texFloodFillA RGBA RGBA8 UNSIGNED_BYTE false false 128 128 128
        image.imgFloodFillB=texFloodFillB RGBA RGBA8 UNSIGNED_BYTE false false 128 128 128
    #elif LIGHTING_VOXEL_SIZE == 64
        image.imgVoxels=texVoxels RED_INTEGER R16UI UNSIGNED_SHORT true false 64 64 64
        image.imgFloodFillA=texFloodFillA RGBA RGBA8 UNSIGNED_BYTE false false 64 64 64
        image.imgFloodFillB=texFloodFillB RGBA RGBA8 UNSIGNED_BYTE false false 64 64 64
    #endif
#else
    program.world-1/shadowcomp.enabled=false
    program.world0/shadowcomp.enabled=false
    program.world1/shadowcomp.enabled=false
#endif

#program.world-1/prepare1.enabled=true
program.world0/prepare1.enabled=false
program.world1/prepare1.enabled=false


#if defined(PHOTONICS) && defined(PHOTONICS_GI_ENABLED)
    image.imgPhotonicsIndirect=texPhotonicsIndirect RGB RGBA16F HALF_FLOAT false true 1.0 1.0
#endif

#ifndef PHOTONICS
    program.world-1/deferred10.enabled=false
    program.world0/deferred10.enabled=false
    program.world1/deferred10.enabled=false
#endif

#if !defined(SSAO_ENABLED) || !(defined(VOXY) || defined(DISTANT_HORIZONS))
    program.world-1/deferred20.enabled=false
    program.world0/deferred20.enabled=false
    program.world1/deferred20.enabled=false

    program.world-1/deferred21.enabled=false
    program.world0/deferred21.enabled=false
    program.world1/deferred21.enabled=false
#endif

customTexture.texLightmap=minecraft:dynamic/lightmap_1

#ifndef LIGHTING_REFLECT_ENABLED
    program.world-1/composite1.enabled=false
    program.world0/composite1.enabled=false
    program.world1/composite1.enabled=false
#endif

##ifdef BLOOM_ENABLED
#    image.imgBloomTiles=texBloomTiles RGB RGBA16F HALF_FLOAT true true 1.0 1.0
##endif

flip.composite80.colortex5=false
flip.composite81.colortex5=false
flip.composite82.colortex5=false
flip.composite83.colortex5=false
flip.composite84.colortex5=false
flip.composite85.colortex5=false
flip.composite86.colortex5=false

#ifndef BLOOM_ENABLED
    program.world-1/composite70.enabled=false
    program.world0/composite70.enabled=false
    program.world1/composite70.enabled=false

    program.world-1/composite87.enabled=false
    program.world0/composite87.enabled=false
    program.world1/composite87.enabled=false
#endif

#if !defined(BLOOM_ENABLED) || BLOOM_LEVELS < 2
    program.world-1/composite71.enabled=false
    program.world0/composite71.enabled=false
    program.world1/composite71.enabled=false

    program.world-1/composite86.enabled=false
    program.world0/composite86.enabled=false
    program.world1/composite86.enabled=false
#endif

#if !defined(BLOOM_ENABLED) || BLOOM_LEVELS < 3
    program.world-1/composite72.enabled=false
    program.world0/composite72.enabled=false
    program.world1/composite72.enabled=false

    program.world-1/composite85.enabled=false
    program.world0/composite85.enabled=false
    program.world1/composite85.enabled=false
#endif

#if !defined(BLOOM_ENABLED) || BLOOM_LEVELS < 4
    program.world-1/composite73.enabled=false
    program.world0/composite73.enabled=false
    program.world1/composite73.enabled=false

    program.world-1/composite84.enabled=false
    program.world0/composite84.enabled=false
    program.world1/composite84.enabled=false
#endif

#if !defined(BLOOM_ENABLED) || BLOOM_LEVELS < 5
    program.world-1/composite74.enabled=false
    program.world0/composite74.enabled=false
    program.world1/composite74.enabled=false

    program.world-1/composite83.enabled=false
    program.world0/composite83.enabled=false
    program.world1/composite83.enabled=false
#endif

#if !defined(BLOOM_ENABLED) || BLOOM_LEVELS < 6
    program.world-1/composite75.enabled=false
    program.world0/composite75.enabled=false
    program.world1/composite75.enabled=false

    program.world-1/composite82.enabled=false
    program.world0/composite82.enabled=false
    program.world1/composite82.enabled=false
#endif

#if !defined(BLOOM_ENABLED) || BLOOM_LEVELS < 7
    program.world-1/composite76.enabled=false
    program.world0/composite76.enabled=false
    program.world1/composite76.enabled=false

    program.world-1/composite81.enabled=false
    program.world0/composite81.enabled=false
    program.world1/composite81.enabled=false
#endif

#if !defined(BLOOM_ENABLED) || BLOOM_LEVELS < 8
    program.world-1/composite77.enabled=false
    program.world0/composite77.enabled=false
    program.world1/composite77.enabled=false

    program.world-1/composite80.enabled=false
    program.world0/composite80.enabled=false
    program.world1/composite80.enabled=false
#endif


#ifdef TAA_ENABLED
    image.imgTAA=texTAA RGBA RGBA16F HALF_FLOAT false true 1.0 1.0
    image.imgTAA_prev=texTAA_prev RGBA RGBA16F HALF_FLOAT false true 1.0 1.0
#else
    program.world1/composite91.enabled=false
    program.world0/composite91.enabled=false
    program.world-1/composite91.enabled=false

    program.world1/composite92.enabled=false
    program.world0/composite92.enabled=false
    program.world-1/composite92.enabled=false
#endif



variable.float.sunViewDist=sqrt(sunPosition.x * sunPosition.x + sunPosition.y * sunPosition.y + sunPosition.z * sunPosition.z)
variable.vec3.sunViewDir=sunPosition / vec3(sunViewDist, sunViewDist, sunViewDist)

variable.vec3.sunWorldDirTemp=vec3(\
    gbufferModelViewInverse.0.0 * sunViewDir.x + gbufferModelViewInverse.1.0 * sunViewDir.y + gbufferModelViewInverse.2.0 * sunViewDir.z, \
    gbufferModelViewInverse.0.1 * sunViewDir.x + gbufferModelViewInverse.1.1 * sunViewDir.y + gbufferModelViewInverse.2.1 * sunViewDir.z, \
    gbufferModelViewInverse.0.2 * sunViewDir.x + gbufferModelViewInverse.1.2 * sunViewDir.y + gbufferModelViewInverse.2.2 * sunViewDir.z)

variable.float.sunLocalDist=sqrt(sunWorldDirTemp.x * sunWorldDirTemp.x + sunWorldDirTemp.y * sunWorldDirTemp.y + sunWorldDirTemp.z * sunWorldDirTemp.z)
uniform.vec3.sunLocalDir=sunWorldDirTemp / vec3(sunLocalDist, sunLocalDist, sunLocalDist)


uniform.float.nearPlane=near
uniform.float.farPlane=far * 5.0
#uniform.float.nearPlane=-gbufferProjection.2.3 / (gbufferProjection.2.2 + 1.0)
#uniform.float.farPlane=gbufferProjection.2.3 / (1.0 - gbufferProjection.2.2)
#uniform.float.nearPlane=gbufferProjection.2.3 / (gbufferProjection.2.2 - 1.0)
#uniform.float.farPlane=gbufferProjection.2.3 / (gbufferProjection.2.2 + 1.0)

uniform.float.far2=gbufferProjection.2.3 / (1.0 - gbufferProjection.2.2)
uniform.float.far3=gbufferProjection.2.3 / (gbufferProjection.2.2 + 1.0)

uniform.vec2.viewSize=vec2(viewWidth, viewHeight)

variable.float.jitter_x = frac(0.75487766624669276005 * frameCounter + 0.5) - 0.5
variable.float.jitter_y = frac(0.56984029099805326591 * frameCounter + 0.5) - 0.5
uniform.vec2.taa_offset = vec2(jitter_x / viewWidth, jitter_y / viewWidth)

variable.float.jitter_prev_x = frac(0.75487766624669276005 * (frameCounter-1) + 0.5) - 0.5
variable.float.jitter_prev_y = frac(0.56984029099805326591 * (frameCounter-1) + 0.5) - 0.5
uniform.vec2.taa_offset_prev = vec2(jitter_prev_x / viewWidth, jitter_prev_y / viewWidth)

uniform.float.windTime = frameTimeCounter

variable.float.weatherF=0.86*rainStrength + 0.14*thunderStrength
uniform.float.weatherStrength=smooth(weatherF, 8, 32)

variable.float.weatherDensityF=mix(mix(0.0004, 0.0012, rainStrength), 0.0048, thunderStrength)
uniform.float.weatherDensity=smooth(weatherDensityF, 8, 32)

variable.float.sunY= clamp((sunLocalDir.y - -0.1) / (0.3 - -0.1), 0.0, 1.0)
uniform.float.skyDayF= sunY*sunY * (3.0 - 2.0*sunY)

#variable.float.windRate = rainstrength * 0.2 + 0.1
#variable.float.windTimeL = smooth(fmod(windTimeL, 1.0), 0.0, 0.5)
#uniform.float.windTime = frac(windTimeL)

#variable.float.windRate = rainStrength * 0.08 + 0.02
#variable.float.windTimeDecay = smooth(if(frameCounter <= 1, 1.0, 0.0), 0.0, 65536.0 / windRate)
#variable.float.windTimeLinear = -log2(windTimeDecay) * 65536.0 * 0.1
#uniform.float.windTime = frac(windTimeLinear) * pi * 10.0
